# Generated by Django 4.2.4 on 2023-08-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageScanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='comment',
            new_name='user_complaint_prose',
        ),
    ]
