# Generated by Django 4.2.4 on 2023-08-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageScanner', '0002_rename_comment_uploadimage_user_complaint_prose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='user_complaint_prose',
            field=models.CharField(max_length=1000),
        ),
    ]
