# Generated by Django 4.2.4 on 2023-08-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageScanner', '0003_alter_uploadimage_user_complaint_prose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='user_complaint_prose',
        ),
    ]
