# Generated by Django 4.2.4 on 2023-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageScanner', '0004_remove_uploadimage_user_complaint_prose'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='user_complaint_prose',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
